apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "/bin/sh", "-c", "env; while true; do sleep 3600; done"]
      env:
        - name: TEMP_VALUE
          valueFrom:
            configMapKeyRef:
              name: my-configmap 
              key: key1
      envFrom:
        - configMapRef:
            name: fromfile 

