apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    kubernetes.io/app: httpd
    kubernetes.io/env: dev
  name: httpd
spec:
  containers:
  - image: httpd
    name: web-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
